from __future__ import annotations

from fmetl.contracts import MirrorAuthority, MirrorContract, PartitionMode


# Exact StarRocks targets maintained by v1_5/sync_strategy_fm.sh.
SYNC_MIRROR_TABLES: tuple[str, ...] = (
    "strategy_fm_sales_di",
    "strategy_fm_purchase_di",
    "strategy_fm_scm_di",
    "strategy_fm_scm_adjust_di",
    "strategy_fm_loss_di",
    "strategy_fm_compose_di",
    "strategy_fm_allowance_di",
    "strategy_fm_promo_di",
    "strategy_fm_inventory_pool_di",
    "strategy_fm_price_da",
    "strategy_fm_dim_day_clear",
    "strategy_fm_dim_store_profile",
    "strategy_fm_purchase_order_tmp",
    "strategy_fm_dim_goods",
    "strategy_fm_receive_sale_di",
    "strategy_fm_order_receive_di",
    "strategy_fm_dim_article_convert",
    "strategy_dim_store_article_bom_relation",
    "strategy_fm_store_article_inventory_detail_di",
    "strategy_fm_full_link_article_di",
    "strategy_fm_store_daily_di",
    "strategy_fm_article_sale_di",
    "strategy_fm_chdj_article_di",
    "strategy_fm_dim_order_saleable",
    "strategy_fm_dim_calendar",
    "strategy_fm_order_offline_di",
    "strategy_fm_order_online_di",
    "strategy_fm_trade_user",
)

# v1.5 reads this native StarRocks application table directly. It is not a
# Hive mirror target and therefore is deliberately separated from the 28-table
# sync allowlist instead of being silently presented as one.
AUXILIARY_STARROCKS_TABLES: tuple[str, ...] = (
    "cuihua_t_purchase_wastage",
)


EXTRACTION_CONTRACTS: dict[str, MirrorContract] = {
    "store_daily": MirrorContract(
        name="strategy_fm_store_daily_di",
        authority=MirrorAuthority.REFERENCE_ONLY,
        partition_column="inc_day",
        store_column="store_id",
        projection=("store_id", "inc_day", "bf19_sale_amt"),
        expected_grain=("store_id", "inc_day"),
        note="Only authorizes valid-business-day selection.",
    ),
    "order_offline": MirrorContract(
        name="strategy_fm_order_offline_di",
        authority=MirrorAuthority.OBSERVATION,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "business_date", "inc_day", "store_id", "order_id", "serial_id",
            "root_order_id", "afs_order_id", "je_order_id", "rje_order_id",
            "pay_at", "abi_article_id", "order_status", "jielong_flag",
            "sales_amt", "qty", "thirdparty_user_identity",
        ),
        expected_grain=("source_row_hash", "duplicate_ordinal"),
        shard_key="order_id",
        shards=16,
        allow_empty=True,
        grain_stage="derived",
        note="Signed events; raw duplicate multiplicity is preserved.",
    ),
    "order_online": MirrorContract(
        name="strategy_fm_order_online_di",
        authority=MirrorAuthority.OBSERVATION,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "business_date", "inc_day", "store_id", "order_id", "serial_id",
            "root_order_id", "afs_order_id", "je_order_id", "rje_order_id",
            "pay_at", "abi_article_id", "order_status", "jielong_flag",
            "sales_amt", "qty", "thirdparty_user_identity",
        ),
        expected_grain=("source_row_hash", "duplicate_ordinal"),
        shard_key="order_id",
        shards=8,
        allow_empty=True,
        grain_stage="derived",
        note="Signed events; raw duplicate multiplicity is preserved.",
    ),
    "trade_user": MirrorContract(
        name="strategy_fm_trade_user",
        authority=MirrorAuthority.OBSERVATION,
        partition_column="inc_day",
        store_column=None,
        projection=("inc_day", "order_id", "thirdparty_user_identity", "trade_time"),
        expected_grain=("inc_day", "order_id"),
        shard_key="order_id",
        shards=8,
        allow_empty=True,
    ),
    "compose": MirrorContract(
        name="strategy_fm_compose_di",
        authority=MirrorAuthority.OBSERVATION,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "store_id", "business_date", "inc_day", "article_id",
            "compose_in_qty", "compose_out_qty", "compose_in_amt", "compose_out_amt",
        ),
        expected_grain=("store_id", "business_date", "article_id"),
        shard_key="article_id",
        shards=4,
        allow_empty=True,
    ),
    "receive_sale": MirrorContract(
        name="strategy_fm_receive_sale_di",
        authority=MirrorAuthority.DERIVED_BRIDGE,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "store_id", "inc_day", "article_id", "article_name",
            "sale_article_id", "sale_article_name", "inbound_qty", "inbound_amount",
            "sum_article_qty", "sum_sub_article_qty", "sale_article_qty",
            "spilit_sale_article_amt", "rate", "sale_recev_rate",
            "category_level1_description",
        ),
        expected_grain=("store_id", "inc_day", "article_id", "sale_article_id"),
        shard_key="article_id",
        shards=8,
        allow_empty=True,
        note="Compatibility plan from upstream DAL; not an original event truth.",
    ),
    "bom_relation": MirrorContract(
        name="strategy_dim_store_article_bom_relation",
        authority=MirrorAuthority.DIMENSION,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "store_id", "inc_day", "parent_article_id", "parent_article_unit",
            "sub_article_id", "sub_article_unit", "dressing_rate", "cost_rate",
            "bom_type", "split_mode", "sp_level", "category_level1_description",
        ),
        expected_grain=("store_id", "inc_day", "parent_article_id", "sub_article_id"),
        shard_key="parent_article_id",
        shards=16,
    ),
    "article_convert": MirrorContract(
        name="strategy_fm_dim_article_convert",
        authority=MirrorAuthority.DIMENSION,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "store_id", "inc_day", "parent_article_id", "parent_article_name",
            "sub_article_id", "sub_article_name", "parent_rate", "sub_rate", "ctype",
        ),
        expected_grain=("store_id", "inc_day", "parent_article_id", "sub_article_id"),
        shard_key="parent_article_id",
        shards=16,
    ),
    "order_receive": MirrorContract(
        name="strategy_fm_order_receive_di",
        authority=MirrorAuthority.DERIVED_BRIDGE,
        partition_column="inc_day",
        store_column="store_id",
        projection=(
            "store_id", "business_date", "inc_day", "order_article_id", "re_article_id",
            "order_qty", "order_amt", "rate", "type", "re_order_qty", "re_order_amt",
        ),
        expected_grain=("store_id", "inc_day", "order_article_id", "re_article_id"),
        required=False,
        shard_key="order_article_id",
        shards=4,
        allow_empty=True,
        note="Historical coverage currently ends 2025-11-17.",
    ),
    "goods": MirrorContract(
        name="strategy_fm_dim_goods",
        authority=MirrorAuthority.DIMENSION,
        partition_column="inc_day",
        store_column=None,
        projection=(
            "inc_day", "article_id", "article_name", "sale_unit", "unit_weight",
            "matnr", "matnr_unit", "order_unit", "atob_value", "zglfz", "zglfm",
            "category_level1_id", "category_level1_description",
            "category_level2_id", "category_level2_description",
            "category_level3_id", "category_level3_description",
            "spu_id", "spu_name", "blackwhite_pig_id", "blackwhite_pig_name",
        ),
        expected_grain=("inc_day", "article_id"),
        shard_key="article_id",
        shards=32,
        partition_mode=PartitionMode.LATEST_SNAPSHOT,
    ),
    "purchase_wastage": MirrorContract(
        name="cuihua_t_purchase_wastage",
        authority=MirrorAuthority.OBSERVATION,
        partition_column="inc_day",
        store_column=None,
        projection=(
            "inc_day", "sku_code", "created_at", "reason", "waste_money",
            "waste_num", "is_deleted",
        ),
        expected_grain=("source_row_hash", "duplicate_ordinal"),
        shard_key="sku_code",
        shards=8,
        managed_by_sync_script=False,
        partition_mode=PartitionMode.LATEST_SNAPSHOT,
        allow_empty=True,
        grain_stage="derived",
        base_predicates=("is_deleted = 0",),
        note="Native StarRocks application source used by v1.5; v0.12 assigns A3XV explicitly.",
    ),
}
