from __future__ import annotations

import argparse
import json
from pathlib import Path

from fmetl import __version__
from fmetl.master_data.category import load_category_mapper
from fmetl.mirror.registry import EXTRACTION_CONTRACTS, SYNC_MIRROR_TABLES
from fmetl.mirror.v014_source import (
    discover_latest_mirror_day,
    extract_and_persist_v014_mirror_sources,
    load_mirror_source_bundle,
    shadow_source_days_ending,
)
from fmetl.mirror.v014_stage import build_v014_stage_bundle, persist_v014_stage_bundle
from fmetl.connectors import QdmApi
from fmetl.connectors.processing_relations import ProcessingRelationSource
from fmetl.validation.preflight import SYNC_SCRIPT_SHA256, validate_mirror_registry, verify_sync_script
from fmetl.validation.run_v014 import run_v014_shadow_week
from fmetl.validation.compare_v014_v15 import (
    compare_v014_to_v15,
    fetch_v15_reference,
    load_v014_result,
    load_v014_relation_articles,
    load_v014_relation_category_effects,
    persist_comparison,
)


def _preflight(sync_script: Path | None) -> int:
    validate_mirror_registry()
    category = load_category_mapper()
    verified_checksum = verify_sync_script(sync_script) if sync_script else None
    payload = {
        "version": __version__,
        "store_id": "A3XV",
        "sync_mirror_table_count": len(SYNC_MIRROR_TABLES),
        "implemented_extraction_contract_count": len(EXTRACTION_CONTRACTS),
        "sync_script_sha256": SYNC_SCRIPT_SHA256,
        "sync_script_verified": verified_checksum is not None,
        "category_rule_version": category.version,
        "frozen_sku_count": len(category.frozen_skus),
        "status": "foundation_ready_not_publishable",
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0


def _processing_relations(path: Path | None):
    if path is None:
        # v0.14 must not apply an undated current recipe to historical days.
        # The dated list endpoint supplies the earliest provable date for the
        # current row version (max(created_at, updated_at)).
        return ProcessingRelationSource().fetch_dated_once().frame
    payload = json.loads(path.read_text(encoding="utf-8"))
    relations = payload.get("relations") if isinstance(payload, dict) else payload
    if not isinstance(relations, list):
        raise ValueError("processing JSON must be a list or contain a relations list")
    import pandas as pd

    frame = pd.DataFrame(relations)
    return frame.rename(columns={
        "finished_sku": "finished_article_id", "raw_sku": "raw_article_id",
    })


def main() -> int:
    parser = argparse.ArgumentParser(description="fmetl development CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)
    preflight = subparsers.add_parser(
        "preflight", help="validate local contracts without production reads or writes"
    )
    preflight.add_argument(
        "--sync-script", type=Path,
        help="optional path to the approved v1_5 sync_strategy_fm.sh for a live checksum comparison",
    )
    shadow = subparsers.add_parser(
        "v014-shadow-week",
        help="read Hive mirrors, normalize internal stages and run a local v0.14 shadow week",
    )
    shadow.add_argument("--store", default="A3XV")
    shadow.add_argument("--end", default="auto")
    shadow.add_argument("--db", type=Path, default=Path("data/fm_v014_shadow.duckdb"))
    shadow.add_argument(
        "--source-db", type=Path, default=Path("data/fm_v014_source.duckdb"),
        help="local cache of field-manual Hive mirror projections",
    )
    shadow.add_argument(
        "--stage-db", type=Path, default=Path("data/fm_v014_stage.duckdb"),
        help="local internal normalization DB generated by this command",
    )
    shadow.add_argument(
        "--processing-json", type=Path,
        help="optional dated processing-relation export; otherwise read the Foodmart API once",
    )
    shadow.add_argument(
        "--reuse-source-cache", action="store_true",
        help="reuse an existing local mirror cache instead of refreshing Hive mirrors",
    )
    mirror = subparsers.add_parser(
        "v014-fetch-mirrors",
        help="read one common seven-day window from Hive-backed mirrors into a local source cache",
    )
    mirror.add_argument("--store", default="A3XV")
    mirror.add_argument("--end", default="auto")
    mirror.add_argument(
        "--source-db", type=Path, default=Path("data/fm_v014_source.duckdb"),
    )
    stage = subparsers.add_parser(
        "v014-build-stage",
        help="programmatically normalize the local Hive-mirror cache into the internal v0.14 stage",
    )
    stage.add_argument("--store", default="A3XV")
    stage.add_argument(
        "--source-db", type=Path, default=Path("data/fm_v014_source.duckdb"),
    )
    stage.add_argument(
        "--stage-db", type=Path, default=Path("data/fm_v014_stage.duckdb"),
    )
    stage.add_argument(
        "--processing-json", type=Path,
        help="optional dated processing-relation export; otherwise read the Foodmart API once",
    )
    compare = subparsers.add_parser(
        "v014-compare-v15",
        help="compare a local v0.14 shadow week with the read-only current v1.5 result",
    )
    compare.add_argument("--db", type=Path, default=Path("data/fm_v014_shadow.duckdb"))
    compare.add_argument(
        "--comparison-db", type=Path, default=Path("data/fm_v014_comparison.duckdb"),
    )
    args = parser.parse_args()
    if args.command == "preflight":
        return _preflight(args.sync_script)
    if args.command == "v014-shadow-week":
        paths = [Path(args.source_db).resolve(), Path(args.stage_db).resolve(), Path(args.db).resolve()]
        if len(set(paths)) != 3:
            raise ValueError("v0.14 source cache, internal stage and output DB must be different files")
        if args.reuse_source_cache:
            mirrors = load_mirror_source_bundle(args.source_db, store_id=args.store)
            run_end = mirrors.requested_days[-1] if args.end == "auto" else args.end
        else:
            run_end = (
                discover_latest_mirror_day(
                    QdmApi(), store_id=args.store, end="auto"
                )
                if args.end == "auto"
                else args.end
            )
            days = shadow_source_days_ending(run_end)
            mirrors = extract_and_persist_v014_mirror_sources(
                store_id=args.store, days=days, path=args.source_db
            )
        stage_bundle = build_v014_stage_bundle(
            mirrors, processing_relations=_processing_relations(args.processing_json)
        )
        persist_v014_stage_bundle(args.stage_db, stage_bundle)
        result = run_v014_shadow_week(
            store_id=args.store,
            end=run_end,
            source_db=args.stage_db,
            output_db=args.db,
        )
        print(json.dumps({
            "version": __version__, "store_id": args.store,
            "start": result.window.start, "end": result.window.end,
            "source_db": str(Path(args.source_db).resolve()),
            "stage_db": str(Path(args.stage_db).resolve()),
            "output_db": str(result.db_path), "result_rows": result.row_count,
            "quarantine_rows": result.quarantine_count,
            "source_provenance": "HIVE_MIRRORS_PLUS_RELATION_EVIDENCE",
            "status": "validated_local_shadow",
        }, ensure_ascii=False, indent=2))
        return 0
    if args.command == "v014-fetch-mirrors":
        source_end = (
            discover_latest_mirror_day(
                QdmApi(), store_id=args.store, end="auto"
            )
            if args.end == "auto"
            else args.end
        )
        days = shadow_source_days_ending(source_end)
        bundle = extract_and_persist_v014_mirror_sources(
            store_id=args.store, days=days, path=args.source_db
        )
        path = Path(args.source_db).resolve()
        print(json.dumps({
            "version": __version__, "store_id": args.store,
            "start": days[0], "end": days[-1], "source_db": str(path),
            "source_table_count": len(bundle.frames),
            "source_provenance": "HIVE_MIRRORS_PLUS_RELATION_EVIDENCE",
            "status": "local_mirror_source_cached",
        }, ensure_ascii=False, indent=2))
        return 0
    if args.command == "v014-build-stage":
        mirrors = load_mirror_source_bundle(args.source_db, store_id=args.store)
        bundle = build_v014_stage_bundle(
            mirrors, processing_relations=_processing_relations(args.processing_json)
        )
        path = persist_v014_stage_bundle(args.stage_db, bundle)
        print(json.dumps({
            "version": __version__, "store_id": args.store,
            "start": bundle.days[0], "end": bundle.days[-1],
            "source_db": str(Path(args.source_db).resolve()),
            "stage_db": str(path), "stage_table_count": len(bundle.frames),
            "quarantine_rows": len(bundle.quarantined),
            "source_provenance": "HIVE_MIRRORS_PLUS_RELATION_EVIDENCE",
            "status": "local_internal_stage_built",
        }, ensure_ascii=False, indent=2))
        return 0
    if args.command == "v014-compare-v15":
        local = load_v014_result(args.db)
        days = tuple(sorted(local["business_date"].astype(str).unique()))
        if len(days) != 7:
            raise ValueError(f"v0.14 comparison requires exactly seven dates, got {days}")
        reference = fetch_v15_reference(QdmApi(), days=days)
        result = compare_v014_to_v15(
            local,
            reference,
            relation_article_ids=load_v014_relation_articles(args.db),
            relation_category_effects=load_v014_relation_category_effects(
                args.db
            ),
        )
        path = persist_comparison(args.comparison_db, result)
        has_failure = result.summary["status"].eq("FAIL").any()
        has_diagnostic = result.summary["status"].eq("DIAGNOSTIC").any()
        print(json.dumps({
            "version": __version__, "start": days[0], "end": days[-1],
            "comparison_db": str(path),
            "summary": result.summary.to_dict("records"),
            "status": (
                "FAIL" if has_failure
                else "PASS_WITH_DIAGNOSTICS" if has_diagnostic
                else "PASS"
            ),
        }, ensure_ascii=False, indent=2))
        return 0
    parser.error(f"unsupported command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
